1.What is Ensemble Learning in machine learning? Explain the key idea behind it.
  Ensemble Learning in ML refers to use of multiple models for making the prediction so as to make the model more stable and accurate.It helps i making tge model more robust.

2.What is the difference between Bagging and Boosting?
  BAGGING- It is the process of training models parallely in which models are independent of each other and it takes diff samples with replacement for training for each model.It is also called Bootstrap Aggregation.
  
  BOOSTING- It is the process of training models sequentially one after the other that are dependent on each other and learn from the mistakes of previous models.

3.What is bootstrap sampling and what role does it play in Bagging methods like Random Forest?
  Bootstrap sampling or bagging the model is trained by taking diff samples with replacement.
  It helps in random forest algorithm by randmoly sampling the rows and features then splitting the data into small chunks thus helps in reducing the overfitting.

4.What are Out-of-Bag OOB samples and how is OOB score used to evaluate ensemble models?
  Out-of-Bag sample is the part of training data not used for training for each individual model.The data whcih is no used for training is used to validate the each secific individual DT. Overall oob score for entire model is taken by taking the average of oob scores of each individual decision trees.

5.Compare feature importance analysis in a single Decision Tree vs. a Random Forest.
  




In [71]:
# Write a Python program to:
# ● Load the Breast Cancer dataset using
# sklearn.datasets.load_breast_cancer()
# ● Train a Random Forest Classifier
# ● Print the top 5 most important features based on feature importance scores.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [72]:
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [73]:
df=pd.DataFrame(data.data,columns=data.feature_names)

In [74]:
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


In [75]:
x = df
y = data.target

In [76]:
from sklearn.model_selection import train_test_split

In [77]:
X_train,x_test,Y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [78]:
from sklearn.ensemble import RandomForestClassifier
rfr=RandomForestClassifier()

In [79]:
rfr.fit(X_train,Y_train)

RandomForestClassifier()

In [80]:
rfr.predict(x_test)

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1])

In [81]:
rfr.feature_importances_

array([0.02741748, 0.01854322, 0.08953421, 0.07357365, 0.00611917,
       0.00632837, 0.04983844, 0.0567386 , 0.00277174, 0.00390232,
       0.00936369, 0.00461782, 0.00957356, 0.01220202, 0.00413046,
       0.00288405, 0.00484445, 0.00333816, 0.00224506, 0.00272186,
       0.11892263, 0.01529938, 0.14925356, 0.12499678, 0.01113987,
       0.01186883, 0.03535734, 0.12891985, 0.00661056, 0.00694285])

In [82]:
for name, importance in zip(data.feature_names, rfr.feature_importances_):
  print(f"{name}: {importance}")

mean radius: 0.02741747821401744
mean texture: 0.01854322189034298
mean perimeter: 0.08953420768221264
mean area: 0.07357364867419482
mean smoothness: 0.006119170583711405
mean compactness: 0.006328374675124846
mean concavity: 0.04983844066999233
mean concave points: 0.05673860137767327
mean symmetry: 0.0027717414990815923
mean fractal dimension: 0.0039023218997748365
radius error: 0.009363693591430307
texture error: 0.0046178227326890055
perimeter error: 0.009573563483154725
area error: 0.012202015345329427
smoothness error: 0.0041304555848478254
compactness error: 0.0028840507496449047
concavity error: 0.004844448044935884
concave points error: 0.0033381608845597533
symmetry error: 0.002245063509568642
fractal dimension error: 0.0027218637215543928
worst radius: 0.1189226301781122
worst texture: 0.015299382750180092
worst perimeter: 0.14925356054636552
worst area: 0.12499677510936376
worst smoothness: 0.01113987217752157
worst compactness: 0.011868828449026824
worst concavity: 0.0353

In [83]:
#7. Write a Python program to:
# ● Train a Bagging Classifier using Decision Trees on the Iris dataset
# ● Evaluate its accuracy and compare with a single Decision Tree
# (Include your Python code and output in the code box below.)

from sklearn.datasets import load_iris

df=load_iris()

In [84]:
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [85]:
x=df.data

In [86]:
y=df.target

In [87]:
from sklearn.model_selection import train_test_split

In [88]:
X_train,x_test,Y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [89]:
from sklearn.tree import DecisionTreeClassifier

In [90]:
DT=DecisionTreeClassifier()

In [91]:
DT

DecisionTreeClassifier()

In [92]:
from sklearn.ensemble import BaggingClassifier

In [93]:
clf=BaggingClassifier(estimator=DT,n_estimators=10,random_state=1)

In [94]:
clf.fit(X_train,Y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), random_state=1)

In [95]:
clf.predict(x_test)

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       1])

In [96]:
from sklearn.metrics import accuracy_score

In [97]:
accuracy_score(y_test,clf.predict(x_test))

0.9555555555555556

In [98]:
DT.fit(X_train,Y_train)

DecisionTreeClassifier()

In [99]:
DT.predict(x_test)

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       1])

In [100]:
accuracy_score(y_test,DT.predict(x_test))

0.9555555555555556

In [101]:
#  8.Write a Python program to:
# ● Train a Random Forest Classifier
# ● Tune hyperparameters max_depth and n_estimators using GridSearchCV
# ● Print the best parameters and final accfrom sklearn.datasets import make_classification

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split


In [102]:
x,y=make_classification(n_samples=1000,n_features=20,random_state=1,n_classes=1)

In [103]:
X_train,x_test,Y_train,y_test=train_test_split(x,y,test_size=.3,random_state=1)

In [104]:
DT

DecisionTreeClassifier()

In [105]:
from sklearn.model_selection import GridSearchCV

In [106]:
params = {"criterion": ["gini", "entropy"],
          "n_estimators": [1, 2, 3, 10, 20, 50, 100],
          "max_depth": [None, 3,4,5,6,10,20
                        ]}

In [107]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(random_state=1)
model = GridSearchCV(rf_classifier, params, cv=5, verbose=3, scoring="accuracy")

In [108]:
model.fit(X_train,Y_train)

Fitting 5 folds for each of 98 candidates, totalling 490 fits
[CV 1/5] END criterion=gini, max_depth=None, n_estimators=1;, score=1.000 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, n_estimators=1;, score=1.000 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, n_estimators=1;, score=1.000 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, n_estimators=1;, score=1.000 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, n_estimators=1;, score=1.000 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, n_estimators=2;, score=1.000 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, n_estimators=2;, score=1.000 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, n_estimators=2;, score=1.000 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, n_estimators=2;, score=1.000 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, n_estimators=2;, score=1.000 total time=   0.0s
[CV 1/5]

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=1),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 3, 4, 5, 6, 10, 20],
                         'n_estimators': [1, 2, 3, 10, 20, 50, 100]},
             scoring='accuracy', verbose=3)

In [109]:
yvalue=model.predict(x_test)

In [110]:
model.best_params_

{'criterion': 'gini', 'max_depth': None, 'n_estimators': 1}

In [111]:
accuracy_score(y_test,yvalue)

1.0

In [112]:
#  Write a Python program to:
# ● Train a Bagging Regressor and a Random Forest Regressor on the California
# Housing dataset
# ● Compare their Mean Squared Errors (MSE)

In [113]:
from sklearn.datasets import fetch_california_housing

In [114]:
df=fetch_california_housing()

In [115]:
x=df.data
y=df.target

In [116]:
from sklearn.model_selection import train_test_split

In [117]:
X_train,x_test,Y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [118]:
from sklearn.ensemble import BaggingRegressor

In [119]:
clf=BaggingRegressor()

In [120]:
clf.fit(X_train,Y_train)

BaggingRegressor()

In [121]:
a=clf.predict(x_test)

In [122]:
from sklearn.ensemble import RandomForestRegressor

In [123]:
model=RandomForestRegressor()

In [124]:
model.fit(X_train,Y_train)

RandomForestRegressor()

In [125]:
b=model.predict(x_test)

In [126]:
from sklearn.metrics import mean_squared_error

In [127]:
mean_squared_error(a,b)

0.034564538785883316

In [127]:
# #  You are working as a data scientist at a financial institution to predict loan
# # default. You have access to customer demographic and transaction history data.
# # You decide to use ensemble techniques to increase model performance.
# # Explain your step-by-step approach to:
# # ● Choose between Bagging or Boosting
# # ● Handle overfitting
# # ● Select base models
# # ● Evaluate performance using cross-validation
# # ● Justify how ensemble learning improves decision-making in this real-world


# 1. Choosing Between Bagging and Boosting
#  Bagging (Bootstrap Aggregating)

# Used when the model has high variance (e.g., Decision Tree)

# Works by training multiple models on different random samples

# Example: Random Forest



# 2. Handling Overfitting

# Overfitting is common in financial datasets.

# Techniques:

# Limit tree complexity:

# max_depth

# min_samples_leaf

# Use regularization (in boosting)


# 3. Selecting Base Models

# The base model is the algorithm used inside the ensemble.

# Common choices:

# Decision Trees (most popular)

# Shallow trees (called weak learners) for boosting




# 4. Evaluate Performance Using Cross-Validation

# Use k-fold cross-validation:

# Steps:

# Split data into k folds (e.g., k = 5)

# Train on k-1 folds and test on remaining fold

# Repeat k times

# Compute average performance

# Metrics to evaluate:

# Accuracy

# Precision (important for false positives)

# Recall (important for catching defaulters)

# F1-score

# ROC-AUC



#5. Benefits in Real World (Loan Default)
# 1. Higher Accuracy

# Combining models reduces errors

# 2. Reduced Risk

# More reliable predictions → fewer bad loans

# 3. Better Generalization

# Works well on unseen customer data

